[theme]
base = "light"
primaryColor = "#111827"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9f9f8"
textColor = "#1f2937"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false